# Site settings
title: Oleg Fedak CV
description: Oleg Fedak CV
favicon: /assets/img/avatar.JPG
baseurl: https://JWebDev.github.io
url: https://JWebDev.github.io
rss_url: /pages/atom.xml

# Author settings
author:
  name: Oleg Fedak
  title: Senior Java Developer / DevOps Engineer
  address: Berlin, Germany
  email: TODO#gmail.com
  link: #
  github: JWebDev
  linkedin: oleg-fedak-b9a03196
  xing: Oleg_Fedak2
#  gavatar: /JWebDev.github.io/assets/img/avatar.JPG
  stackoverflow:
#    stackoverflow: 1590594
  workHistory:
    - work1:
      company: kv.digital GmbH
      location: Berlin, Germany
      title: DevOps Engineer
      started: 2020
      duration: (2020 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: KV Telematik GmbH
      location: Berlin, Germany
      title: Senior Java Developer / DevOps Engineer
      started: 2017
      duration: (2017 - 2020)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: <s>primervoto GmbH</s> -> Solactive AG
      location: Berlin, Germany
      title: Senior Java Developer
      started: 2017
      duration: (2017 - 2017)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work4:
      company: Klopotek AG
      location: Berlin, Germany
      title: Java Backend Developer / Frontend Developer
      started: 2014
      duration: (2014 - 2017)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work5:
      company: <s>xx-well gmbh</s> -> <s>Welldoo GmbH</s> -> Vilua Healthcare GmbH
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work6:
      company: <s>Steria Mummert Consulting GmbH</s> -> Sopra Steria SE
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2011
      duration: (2011 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work7:
      company: Computer Center "Cluster"
      location: Ternopil, Ukraine
      title: Repair of computers
      started: 2007
      duration: (2007 - 2008)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work8:
      company: Konica Minolta
      location: Ternopil, Ukraine
      title: Designer and video editing
      started: 2006
      duration: (2006 - 2007)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work9:
      company: Computer Center "Terminal"
      location: Ternopil, Ukraine
      title: Computer network administrator
      started: 2006
      duration: (2006 - 2006)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work10:
      company: Internet cafe "Krapka"
      location: Ternopil, Ukraine
      title: Internet cafe administrator
      started: 2005
      duration: (2005 - 2006)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Hochschule für Technik und Wirtschaft Berlin (University of Applied Sciences)
      location: Berlin, Germany
      degree: Bachelor of Science
      major: Applied computer science (Angewandte Informatik)
      started: 2011
      duration: (2011 - 2014)
      description:
    - education2:
      organization: Hochschule Osnabrück (University of Applied Sciences)
      location: Osnabrück, Germany
      degree: Bachelor of Science
      major: Media informatics (Medieninformatik)
      started: 2008
      duration: (2008 - 2011)
      description:
    - education3:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Master of Science
      major: Computer sciences
      started: 2007
      duration: (2007 - 2008)
      description:
    - education4:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Bachelor of Science
      major: Computer sciences
      started: 2005
      duration: (2005 - 2007)
      description:
    - education5:
      organization: Vyacheslav Chornovil Galician College
      location: Ternopil, Ukraine
      degree: Diploma of qualified specialist degree
      major: Computer science, operation of data processing and decision systems
      started: 2001
      duration: (2001 - 2005)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%