# Site settings
title: Oleg Fedak CV
description: Oleg Fedak CV
favicon: /assets/img/avatar.JPG
baseurl: https://JWebDev.github.io
url: https://JWebDev.github.io
rss_url: /pages/atom.xml

# Author settings
author:
  name: Oleg Fedak
  title: DevOps Engineer / Senior Java Developer
  address: Berlin, Germany
  email: surnamename#gmail.com
  link: #
  github: JWebDev
  linkedin: oleg-fedak-b9a03196
  xing: Oleg_Fedak2
  stackoverflow:
  #    stackoverflow: 1590594
  workHistory:
    - work1:
      company: kv.digital GmbH
      location: Berlin, Germany
      title: DevOps Engineer
      started: 2020
      duration: (2020 - Present)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Docker, Jenkins, Jenkins Pipelines, Nexus, Java 11, MySQL, Spring Boot. Spring Boot Admin, Maven, Ansible, Groovy, Python, SonarQube
    - work2:
      company: KV Telematik GmbH
      location: Berlin, Germany
      title: Senior Java Developer / DevOps Engineer
      started: 2017
      duration: (2017 - 2020)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Java 8/11, MySQL, Spring Boot. Spring Security, Hibernate, Maven, Jersey, Nexus, Jenkins, Docker, OpenAPI, Liquibase, SonarQube
    - work3:
      company: <s>Primervoto GmbH</s> &#8594 Solactive AG
      location: Berlin, Germany
      title: Senior Java Developer
      started: 2017
      duration: (2017 - 2017)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Java 8, MySQL, Spring Boot. Hibernate, Maven, sbt, Play Framework, RESTEasy
    - work4:
      company: Klopotek AG
      location: Berlin, Germany
      title: Java Backend Developer / Frontend Developer
      started: 2014
      duration: (2014 - 2017)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Java 7/8, Oracle, Spring. Hibernate, Maven, AWS, Ansible, GitLab, JFrog, Jenkins, Wildfly, AngularJS
    - work5:
      company: <s>xx-well GmbH</s> &#8594 <s>Welldoo GmbH</s> &#8594 Vilua Healthcare GmbH
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2012
      duration: (2012 - 2014)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Java 6/7, Oracle 11g, Apache Tomcat, Spring MVC/Data/Web Flow. Hibernate, Maven, Flyway, Swagger, Mockito, Jersey
    - work6:
      company: <s>Steria Mummert Consulting GmbH</s> &#8594 Sopra Steria SE
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2011
      duration: (2011 - 2012)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Java, JavaEE, JavaScript, ExtJS, jQuery, JFreeChart
    - work7:
      company: Computer Center "Cluster"
      location: Ternopil, Ukraine
      title: Repair of computers
      started: 2007
      duration: (2007 - 2008)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies:
    - work8:
      company: Konica Minolta
      location: Ternopil, Ukraine
      title: Designer and video editing
      started: 2006
      duration: (2006 - 2007)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Adobe Photoshop, Adobe Illustrator, CorelDraw, Adobe Premiere, Adobe After Effects, Flash, ActionScript, C++ Builder
    - work9:
      company: Computer Center "Terminal"
      location: Ternopil, Ukraine
      title: Computer network administrator
      started: 2006
      duration: (2006 - 2006)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies:
    - work10:
      company: Internet cafe "Krapka"
      location: Ternopil, Ukraine
      title: Internet cafe administrator
      started: 2005
      duration: (2005 - 2006)
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies:
  projects:
    - project1:
      name: Concurrent Analytics
      started: 2017
      duration: 2017-Present
      link: <a href="http://concurrent-analytics.com" target="_blank"> www.concurrent-analytics.com </a>
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies: Kubernetes, Docker, Terraform, Apache Spark. HDFS, Helm. Elasticsearch, Kibana, Fluent Bit, Ansible, Prometheus, Grafana, MySQL, MongoDB, Angular, TeamCity, Kotlin, Nexus, Shell
    - project2:
      name: Words Tutor
      started: 2016
      duration: 2016-2017
      link: <a href="https://play.google.com/store/apps/details?id=com.jdev.tutor" target="_blank"> Words Tutor on PlayMarket </a>
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies:  Java, Android
    - project3:
      name: Other
      started: 2012
      duration: 2012-2014
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies:  Java, Java Swing, Objective C, Cocoa, Android
  educationHistory:
    - education1:
      organization: Hochschule für Technik und Wirtschaft Berlin (University of Applied Sciences)
      location: Berlin, Germany
      degree: Bachelor of Science
      major: Applied computer science (Angewandte Informatik)
      started: 2011
      duration: (2011 - 2014)
      description:
    - education2:
      organization: Hochschule Osnabrück (University of Applied Sciences)
      location: Osnabrück, Germany
      degree: Bachelor of Science
      major: Media informatics (Medieninformatik)
      started: 2008
      duration: (2008 - 2011)
      description:
    - education3:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Master of Science
      major: Computer sciences
      started: 2007
      duration: (2007 - 2008)
      description:
    - education4:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Bachelor of Science
      major: Computer sciences
      started: 2005
      duration: (2005 - 2007)
      description:
    - education5:
      organization: Vyacheslav Chornovil Galician College
      location: Ternopil, Ukraine
      degree: Diploma of qualified specialist degree
      major: Computer science, operation of data processing and decision systems
      started: 2001
      duration: (2001 - 2005)
      description:
  languages:
    - language1:
      name: English
      proficiency: Proficient
    - language2:
      name: German
      proficiency: Proficient
    - language3:
      name: Ukrainian
      proficiency: Native
    - language4:
      name: Russian
      proficiency: Native
  skills:
    - skill1:
      name: Java
      percentage: 100%
    - skill2:
      name: Spring / Spring Boot
      percentage: 90%
    - skill3:
      name: Docker
      percentage: 90%
    - skill4:
      name: Jenkins
      percentage: 80%
    - skill5:
      name: Kubernetes
      percentage: 60%
    - skill6:
      name: Terraform
      percentage: 60%
    - skill7:
      name: Nexus
      percentage: 80%
    - skill8:
      name: Databases
      percentage: 75%
    - skill9:
      name: Python
      percentage: 65%
    - skill10:
      name: Go
      percentage: 60%
  interestedon:
    - skill1:
      name: Data Engineering
      percentage: 100%
    - skill2:
      name: DevOps
      percentage: 100%
    - skill3:
      name: Clouds
      percentage: 100%
    - skill4:
      name: BigData
      percentage: 100%
    - skill5:
      name: Kubernetes
      percentage: 100%
    #    - skill6:
    #      name: Terraform
    #      percentage: 80%
    #    - skill7:
    #      name: Java
    #      percentage: 70%
    #    - skill8:
    #      name: Databases
    #      percentage: 75%
    #    - skill9:
    #      name: Python
    #      percentage: 80%
    #    - skill10:
    #      name: Go
    #      percentage: 80%
  languagesskills: [Java, Python, Go, Bash, SQL, JavaScript, Groovy]
  frameworksskills: [Spring, Spring Boot, Apache Spark, Angular, Android SDK]