# Site settings
title: Oleg Fedak CV
description: Oleg Fedak CV
favicon: /assets/img/avatar.JPG
baseurl: https://JWebDev.github.io
url: https://JWebDev.github.io
rss_url: /pages/atom.xml

# Author settings
author:
  name: Oleg Fedak
  title: DevOps Engineer / Senior Java Developer
  address: Berlin, Germany
  email: surnamename#gmail.com
  link: #
  github: JWebDev
  linkedin: oleg-fedak-b9a03196
  xing: Oleg_Fedak2
  stackoverflow:
  #    stackoverflow: 1590594
  workHistory:
    - work1:
      company: kv.digital GmbH
      location: Berlin, Germany
      title: DevOps Engineer
      started: 2020
      duration: (2020 - Present)
      description: [<li>Created and maintained SonarQube Server.</li>
                      <li>Dockerizing microservices for rapidl development and deployment, Relational/NoSQL Databases, other tools and frameworks.</li>
                      <li>Created and maintained Jenkins to execute the continuous integration of code to ensure the quality of the code.</li>
                      <li>Built Jenkins CI/CD pipelines in Groovy to automate the code releases, building Docker containers and updating Confluence/JIRA states through REST API.</li>
                      <li>Cron Jobs for cleaning outdated projects/branches etc.</li>
                      <li>Built a continuous delivery pipelines using Jenkins to support the continuous development process.</li>
                      <li>Python scripts for Jenkins and Nexus migrations.</li>
                      <li>Improvement and adjustment of processes between Development and Operations teams.</li>
                      <li>Introduced Spring Boot Admin for a better overview of metrics.</li>
      ]
      technologies: Docker, Jenkins, Jenkins Pipelines, Nexus, Java 11, MySQL, Spring Boot. Spring Boot Admin, Maven, Ansible, Groovy, Python, SonarQube
    - work2:
      company: KV Telematik GmbH
      location: Berlin, Germany
      title: Senior Java Developer / DevOps Engineer
      started: 2017
      duration: (2017 - 2020)
      description: [<li>Development and support of a complex CQRS system.</li>
                      <li>Development in a small team of a highly customizable healthcare product.</li>
                      <li>Development doctor/practice search platform using Apache Lucene search engine.</li>
                      <li>Protected administrator's office access to configure the system.</li>
                      <li>Created infrastructure, test and dev environments with Docker, CI/CD and programmed Microservices.</li>
                      <li>OpenAPI Specification for the system.</li>
                      <li>Systems used to program the project&#58 Spring Boot/Spring Security/Hibernate/Angular.</li>
                      <li>Built Jenkins CI/CD pipelines in Groovy to automate all processes.</li>
                      <li>System support Support system with updated and patched libraries to increase security.</li>
      ]
      technologies: Java 8/11, MySQL, Spring Boot. Spring Security, Hibernate, Maven, Jersey, Nexus, Jenkins, Docker, OpenAPI, Liquibase, SonarQube
    - work3:
      company: <s>Primervoto GmbH</s> &#8594 Solactive AG
      location: Berlin, Germany
      title: Senior Java Developer
      started: 2017
      duration: (2017 - 2017)
      description: [<li>Development of services for financial exchange. Most used technologies for development&#58 Java 8, Spring Boot, Play Framework, MySQL, Maven, sbt, etc.</li>
      ]
      technologies: Java 8, MySQL, Spring Boot. Hibernate, Maven, sbt, Play Framework, RESTEasy
    - work4:
      company: Klopotek AG
      location: Berlin, Germany
      title: Java Backend Developer / Frontend Developer
      started: 2014
      duration: (2014 - 2017)
      description: [<li>Development of software for more than 350 publishing houses.</li>
                      <li>Big migration from JBoss to WildFly.</li>
                      <li>Creating and implementing microservices with Spring, Oracle, Maven, Hibernate etc.</li>
                      <li>CI/CD with Gitlab, Artifactory, JFrog, Jenkins etc.</li>
                      <li>Developing Web Frontend with AngularJS.</li>
      ]
      technologies: Java 7/8, Oracle, Spring. Hibernate, Maven, AWS, Ansible, GitLab, JFrog, Jenkins, Wildfly, AngularJS
    - work5:
      company: <s>xx-well GmbH</s> &#8594 <s>Welldoo GmbH</s> &#8594 Vilua Healthcare GmbH
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2012
      duration: (2012 - 2014)
      description: [<li>Development of software for eHealth and other areas.</li>
                      <li>Developing and maintaining microservices with Java, Spring, Oracle, Maven, Hibernate etc.</li>
                      <li>Swagger for REST documentation, Flyway for database migrations.</li>
                      <li>Maintenance of JSP/JSF Web Frontend.</li>
                      <li>Bachelor thesis “Microservices Architecture”.</li>
      ]
      technologies: Java 6/7, Oracle 11g, Apache Tomcat, Spring MVC/Data/Web Flow. Hibernate, Maven, Flyway, Swagger, Mockito, Jersey
    - work6:
      company: <s>Steria Mummert Consulting GmbH</s> &#8594 Sopra Steria SE
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2011
      duration: (2011 - 2012)
      description: [<li>Development of software for GAS-X project.</li>
                      <li>Developing with Java, JavaEE, JavaScript, JQuery, ExtJS etc.</li>
                      <li>Research and prototyping of SpreadSheet web components.</li>
                      <li>Research tasks for replacement of Active-X components.</li>
      ]
      technologies: Java, JavaEE, JavaScript, ExtJS, jQuery, JFreeChart
    - work7:
      company: Computer Center "Cluster"
      location: Ternopil, Ukraine
      title: Repair of computers
      started: 2007
      duration: (2007 - 2008)
      description: [<li>Repair, maintenance and assembly of computer hardware.</li>
                      <li>Virus removal, cleaning. Installations of operating systems. HDD backups.</li>
      ]
      technologies:
    - work8:
      company: Konica Minolta
      location: Ternopil, Ukraine
      title: Designer and video editing
      started: 2006
      duration: (2006 - 2007)
      description: [<li>Worker in a photo/design studio.</li>
                      <li>Retouching, mounting, restoration, business cards, collages, posters, banners with Adobe Photoshop, Adobe Illustrator and CorelDraw.</li>
                      <li>Video montage with Adobe Premiere and Adobe After Effects.</li>
                      <li>Web banners with Flash and ActionScript.</li>
                      <li>Programmed cost accounting system using C++ Builder.</li>
      ]
      technologies: Adobe Photoshop, Adobe Illustrator, CorelDraw, Adobe Premiere, Adobe After Effects, Flash, ActionScript, C++ Builder
    - work9:
      company: Computer Center "Terminal"
      location: Ternopil, Ukraine
      title: Computer network administrator
      started: 2006
      duration: (2006 - 2006)
      description: [<li>Created, configured, built and maintained of internet networks for customers.</li>
      ]
      technologies:
    - work10:
      company: Internet cafe "Krapka"
      location: Ternopil, Ukraine
      title: Internet cafe administrator
      started: 2005
      duration: (2005 - 2006)
      description: [<li>Customer service in the Internet cafe, support for the health and performance of computers, session control, setting up network games.</li>
      ]
      technologies:
  projects:
    - project1:
      name: Concurrent Analytics
      started: 2017
      duration: 2017-Present
      link: <a href="http://concurrent-analytics.com" target="_blank"> <u>www.concurrent-analytics.com</u> </a>
      description: [<li>Created from scratch a kubernetes cluster for big data processing, data analytics, computing and machine learning using Apache Spark.</li>
                      <li>Developed an entire infrastructure as Infrastructure-as-Code using Ansible, later rewritten using Terraform.</li>
                      <li>Cluster logging&#58 Elasticserach, Kibana, Fluent Bit, Metricbeat.</li>
                      <li>Cluster monitoring&#58 Prometheus and Grafana.</li>
                      <li>Spark ecosystem&#58 Standalone Spark cluster with worker nodes, Spark history server, HDFS storage.</li>
                      <li>Spring Boot Service as Backend with MySQL and MongoDB and Web Frontend with Angular.</li>
                      <li>Autonomous TeamCity CI/CD server react to webhooks and takes an automatic deploy/redeploy.</li>
                      <li>All TeamCity Pipelines developed as a code with Kotlin.</li>
                      <li>Nexus as a repository for artefacts and docker images.</li>
                      <li>Apache Zeppelin for fast access to Spark cluster.</li>
                      <li>Helm as package manager for Kubernetes.</li>
      ]
      technologies: Kubernetes, Docker, Terraform, Apache Spark. HDFS, Helm. Elasticsearch, Kibana, Fluent Bit, Ansible, Prometheus, Grafana, MySQL, MongoDB, Angular, TeamCity, Kotlin, Nexus, Shell
    - project2:
      name: Words Tutor
      started: 2016
      duration: 2016-2017
      link: <a href="https://play.google.com/store/apps/details?id=com.jdev.tutor" target="_blank"> <u>Words Tutor on PlayMarket</u> </a>
      description: [<li>I am not a description1. I am not description.I am not description.</li>
                      <li>I am not a description2. I am not description.I am not description.</li>
                      <li>I am not a description3. I am not description.I am not description.</li>
                      <li>I am not a description4. I am not description.I am not description.</li>
                      <li>I am not a description5. I am not description.I am not description.</li>
      ]
      technologies:  Java, Android
    - project3:
      name: Other
      started: 2012
      duration: 2012-2014
      description: >
      <li>A chess game developed using Java Sockets and Java Swing with following features&#58 local and network game,
      2D chess board, 2-player mode, clock, chat, save/continue network game, animation during figure selection.</li>
      <li>A “Sudoku" game with game generation algorithm, level of complexity and a database storage for iPhone using Objective C and Cocoa.</li>
      <li>A “MapTracker” project developed using Android. The aim of the project&#58 to save the GPS coordinates
      during the movement using the background service and then to play the trip in Google 3D Maps.</li>
      technologies:  Java, Java Swing, Objective C, Cocoa, Android
  educationHistory:
    - education1:
      organization: Hochschule für Technik und Wirtschaft Berlin (University of Applied Sciences)
      location: Berlin, Germany
      degree: Bachelor of Science
      major: Applied computer science (Angewandte Informatik)
      started: 2011
      duration: (2011 - 2014)
      description:
    - education2:
      organization: Hochschule Osnabrück (University of Applied Sciences)
      location: Osnabrück, Germany
      degree: Bachelor of Science
      major: Media informatics (Medieninformatik)
      started: 2008
      duration: (2008 - 2011)
      description:
    - education3:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Master of Science
      major: Computer sciences
      started: 2007
      duration: (2007 - 2008)
      description:
    - education4:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Bachelor of Science
      major: Computer sciences
      started: 2005
      duration: (2005 - 2007)
      description:
    - education5:
      organization: Vyacheslav Chornovil Galician College
      location: Ternopil, Ukraine
      degree: Diploma of qualified specialist degree
      major: Computer science, operation of data processing and decision systems
      started: 2001
      duration: (2001 - 2005)
      description:
  languages:
    - language1:
      name: English
      proficiency: Proficient
    - language2:
      name: German
      proficiency: Proficient
    - language3:
      name: Ukrainian
      proficiency: Native
    - language4:
      name: Russian
      proficiency: Native
  skills:
    - skill1:
      name: Java
      percentage: 100%
    - skill2:
      name: Spring / Spring Boot
      percentage: 90%
    - skill3:
      name: Docker
      percentage: 90%
    - skill4:
      name: Jenkins
      percentage: 80%
    - skill5:
      name: Kubernetes
      percentage: 60%
    - skill6:
      name: Terraform
      percentage: 60%
    - skill7:
      name: Nexus
      percentage: 80%
    - skill8:
      name: Databases
      percentage: 75%
    - skill9:
      name: Python
      percentage: 65%
    - skill10:
      name: Go
      percentage: 60%
  expiriences:
    - skill1:
      name: Java
      label: 10 years
      percentage: 100%
    - skill2:
      name: Spring / Spring Boot
      label: 8 years
      percentage: 80%
    - skill3:
      name: Linux
      label: 8 years
      percentage: 80%
    - skill4:
      name: Databases
      label: 8 years
      percentage: 80%
    - skill5:
      name: Jenkins
      label: 6 years
      percentage: 60%
    - skill6:
      name: Docker
      label: 5 years
      percentage: 50%
    - skill7:
      name: CI/CD
      label: 5 years
      percentage: 50%
    - skill8:
      name: Kubernetes
      label: 4 years
      percentage: 40%
    - skill9:
      name: DevOps
      label: 4 years
      percentage: 40%
    - skill10:
      name: Terraform
      label: 1 year
      percentage: 10%
  interestedon:
    - skill1:
      name: Data Engineering
      percentage: 100%
    - skill2:
      name: DevOps
      percentage: 100%
    - skill3:
      name: Clouds
      percentage: 100%
    - skill4:
      name: BigData
      percentage: 100%
    - skill5:
      name: Kubernetes
      percentage: 100%
    #    - skill6:
    #      name: Terraform
    #      percentage: 80%
    #    - skill7:
    #      name: Java
    #      percentage: 70%
    #    - skill8:
    #      name: Databases
    #      percentage: 75%
    #    - skill9:
    #      name: Python
    #      percentage: 80%
    #    - skill10:
    #      name: Go
    #      percentage: 80%
  environment_skills: [Linux/MacOS, IntelliJ IDEA, Docker, Shell, Git]
  languages_skills: [Java, Python, Go, Bash, SQL, JavaScript, Groovy]
  frameworks_skills: [Spring, Spring Boot, Apache Spark, Angular, Android SDK]
  paradigms_skills: [DevOps, Object-oriented Programming (OOP), CQRS, Agile Software Development(Scrum/Kanban), Dependency Injection, Microservices, Microservices Architecture, Continuous Integration (CI), Continuous Development (CD), Continuous Delivery (CD), REST, Unit/Integrations Testing, UML]
  storage_skills: [MySQL, Oracle, MongoDB, SQLite]
  tools_skills: [IntellJ IDEA, Gradle, Maven, sbt, Git, Jenkins, TeamCity, Nexus, SonarQube, Portainer, Visual Studio Code, Android Studio, Terraform, Kibana, Grafana]
  platforms_skills: [Kubernetes, Docker, Android, AWS, Vagrant, Linux, MacOS, Windows]
  libraries_skills: [Apache Lucene, Apache CXF, Jersey, RESTEasy, Flyway, Liquibase, Guava, JUnit, TestNG, Mockito, OpenAPI(Swagger), JAX-RS, Bean Validation, JPA]