# Site settings
title: Oleg Fedak CV
description: Oleg Fedak CV
favicon: /assets/img/avatar.JPG
baseurl: https://JWebDev.github.io
url: https://JWebDev.github.io
rss_url: /pages/atom.xml

# Author settings
author:
  name: Oleg Fedak
  title: Senior DevOps Engineer / Senior Java Developer
  address: Berlin, Germany
  email: surnamename#gmail.com
  link: #
  github: JWebDev
  linkedin: oleg-fedak-b9a03196
  xing: Oleg_Fedak2
  lastUpdateDate: " Last Update: 23.12.2021"
  workHistory:
    - work1:
      company: kv.digital GmbH
      location: Berlin, Germany
      title: Senior DevOps Engineer
      started: 2021
      duration: (2021 - Present)
      description: >
        <ul><li>Transformation of the infrastructure to move Microservices to Kubernetes.</li>
        <li>Installation and configuration of the Kubernetes cluster for test systems.</li>
        <li>Setting up a load balancer, storage, monitoring, logging, security and everything that is needed for the full operation of applications.</li>
        <li>Planning and implementation of Kubernetes CI/CD Pipelines for dynamic environments for different purposes.</li>
        <li>Training and education of fellow administrators of the Kubernetes platform.</li></ul>
      technologies: Kubernetes, Rancher, Traefik, Prometheus, Grafana, OpenSearch, HashiCorp Vault, Helm, Longhorn, Argo-cd/workflows/events/rollouts, Harbor, Lens, kubectl
    - work2:
      company: kv.digital GmbH
      location: Berlin, Germany
      title: Senior DevOps Engineer
      started: 2020
      duration: (2020 - 2021)
      description: >
        <ul><li>Built infrastructure for COVID-19 vaccination appointment booking system, including planning and maintenance, which was implemented across the entire Germany. <a href="https://www.impfterminservice.de" target="_blank"><u>https://www.impfterminservice.de</u></a></li>
        <li>Planned, created and maintained the monitoring system for microservices to evaluate the internal specific metrics and behavior of the microservice in real time.</li>
        <li>Creation of product testing system and full automation of various types of tests (scenarios, performance, GUI ..) for different runtime environments.</li>
        <li>Dockerizing microservices for rapid development and deployment, Relational/NoSQL Databases, other tools and frameworks.</li>
        <li>Set up and maintained SonarQube Server.</li>
        <li>Set up and maintained Jenkins to execute the continuous integration to ensure the quality of the code.</li>
        <li>Built Jenkins CI/CD pipelines in Groovy to automate the code releases, building Docker containers and updating Confluence/JIRA states through REST API.</li>
        <li>Developed cron Jobs for cleaning outdated projects/branches etc.</li>
        <li>Built a continuous delivery pipelines using Jenkins to support the continuous development process.</li>
        <li>Python scripts for Jenkins and Nexus migrations.</li>
        <li>Improvement and adjustment of processes between Development and Operations teams.</li>
        <li>Creation of infrastructure for the web projects and integration in CI/CD processes.</li>
        <li>OWASP checks and analysis of Artifacts for security bugs and vulnerabilities.</li>
        <li>Introduced Spring Boot Admin for a better overview of metrics.</li></ul>
      technologies: Elasticsearch, Kibana, Grafana, Prometheus, Groovy, Shell, Docker, Jenkins, Jenkins Pipelines, Nexus, Java 11, MySQL, Spring Boot, Spring Boot Admin, Maven, Ansible, Python, SonarQube
    - work3:
      company: KV Telematik GmbH
      location: Berlin, Germany
      title: Senior Java Developer / DevOps Engineer
      started: 2017
      duration: (2017 - 2020)
      description: >
        <ul><li>Development and support of a complex CQRS system.</li>
        <li>Development in a small team of a highly customizable healthcare product.</li>
        <li>Development doctor/practice search platform using Apache Lucene search engine.</li>
        <li>Protected administrator's access to configure the system.</li>
        <li>Created infrastructure, test and dev environments with Docker, CI/CD and programmed Microservices.</li>
        <li>OpenAPI Specification for the project development.</li>
        <li>Systems used to program the project&#58 Spring Boot, Spring Security, Hibernate, Angular, etc.</li>
        <li>Built Jenkins CI/CD pipelines in Groovy to automate all processes.</li>
        <li>Updated and patched libraries to increase security.</li></ul>
      technologies: Java 8/11, MySQL, Spring Boot. Spring Security, Hibernate, Maven, Jersey, Nexus, Jenkins, Docker, OpenAPI, Liquibase, SonarQube
    - work4:
      company: Solactive AG (formerly known as Primervoto GmbH)
      location: Berlin, Germany
      title: Senior Java Developer
      started: 2017
      duration: (2017 - 2017)
      description: Development of services for financial exchange. Most used technologies for development&#58 Java 8, Spring Boot, Play Framework, MySQL, Maven, sbt, etc.
      technologies: Java 8, MySQL, Spring Boot. Hibernate, Maven, sbt, Play Framework, RESTEasy
    - work5:
      company: Klopotek AG
      location: Berlin, Germany
      title: Java Backend Developer / Frontend Developer
      started: 2014
      duration: (2014 - 2017)
      description: >
        <ul><li>Development of software for more than 350 publishing houses.</li>
        <li>Big migration from JBoss to WildFly.</li>
        <li>Created and implemented microservices with Spring, Oracle, Maven, Hibernate, etc.</li>
        <li>CI/CD with Gitlab, Artifactory, JFrog, Jenkins, etc.</li>
        <li>Developed Web Frontend with AngularJS.</li>
        <li>Automated deployment to AWS with Ansible.</li></ul>
      technologies: Java 7/8, Oracle, Spring. Hibernate, Maven, AWS, Ansible, GitLab, JFrog, Jenkins, Wildfly, AngularJS
    - work6:
      company: Vilua Healthcare GmbH (formerly known as xx-well GmbH and Welldoo GmbH)
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2012
      duration: (2012 - 2014)
      description: >
        <ul><li>Development of software for eHealth and other areas.</li>
        <li>Developed and maintained microservices with Java, Spring, Oracle, Maven, Hibernate, etc.</li>
        <li>Swagger for REST documentation, Flyway for database migrations.</li>
        <li>Maintenance of JSP/JSF Web Frontend.</li>
        <li>Bachelor thesis “Microservices Architecture”.</li></ul>
      technologies: Java 6/7, Oracle 11g, Apache Tomcat, Spring MVC/Data/Web Flow. Hibernate, Maven, Flyway, Swagger, Mockito, Jersey
    - work7:
      company: Sopra Steria SE (formerly known as Steria Mummert Consulting GmbH)
      location: Berlin, Germany
      title: Working student (Java Backend Developer / Frontend Developer)
      started: 2011
      duration: (2011 - 2012)
      description: >
        <ul><li>Development of software for GAS-X project.</li>
        <li>Development using Java, JavaEE, JavaScript, JQuery, ExtJS etc.</li>
        <li>Research and prototyping of SpreadSheet web components.</li>
        <li>Research tasks for replacement of Active-X components.</li></ul>
      technologies: Java, JavaEE, JavaScript, ExtJS, jQuery, JFreeChart
    - work8:
      company: Computer Center "Cluster"
      location: Ternopil, Ukraine
      title: Repair of computers
      started: 2007
      duration: (2007 - 2008)
      description: >
        <ul><li>Repair, maintenance and assembly of computer hardware.</li>
        <li>Virus removal, cleaning.</li>
        <li>Installation of operating systems. HDD backups.</li></ul>
      technologies:
    - work9:
      company: Konica Minolta
      location: Ternopil, Ukraine
      title: Designer and video editing
      started: 2006
      duration: (2006 - 2007)
      description: >
        <ul><li>Designer in a photo/design studio.</li>
        <li>Retouching, mounting, restoration, business cards, collages, posters, banners with Adobe Photoshop, Adobe Illustrator and CorelDraw.</li>
        <li>Video montage with Adobe Premiere and Adobe After Effects.</li>
        <li>Web banners with Flash and ActionScript.</li>
        <li>Programmed cost accounting system using C++ Builder.</li></ul>
      technologies: Adobe Photoshop, Adobe Illustrator, CorelDraw, Adobe Premiere, Adobe After Effects, Flash, ActionScript, C++ Builder
    - work10:
      company: Computer Center "Terminal"
      location: Ternopil, Ukraine
      title: Computer network administrator
      started: 2006
      duration: (2006 - 2006)
      description: Created, configured, built and maintained internet networks for customers.
      technologie§s:
    - work10:
      company: Internet cafe "Krapka"
      location: Ternopil, Ukraine
      title: Internet cafe administrator
      started: 2005
      duration: (2005 - 2006)
      description: Customer service in the Internet cafe, performance support of computers, session control, setting up network games.
      technologies:
  projects:
    - project1:
      name: Kube Helper
      started: 2020
      duration: 2020-Present
      title: Founder
      link: <a href="https://github.com/KubeHelper/kubehelper" target="_blank"> <u>https://github.com/KubeHelper/kubehelper</u></a>
      description: >
        <ul><li>KubeHelper - an Open Source product developed from the scratch.</li>
        <li>KubeHelper is a tool that simplifies many of the daily tasks associated with managing Kubernetes through a web interface. Search, analysis, run commands, cron jobs, reports, filters, git synchronization and many more.</li>
        <li>Read more about the KubeHelper project on wiki.<a href="https://github.com/KubeHelper/kubehelper/wiki" target="_blank"> <u>https://github.com/KubeHelper/kubehelper/wiki</u></a></li></ul>
      technologies: Kubernetes, Terraform, Helm, Docker, Java, Spring Boot, Shell, Zk Framework
    - project2:
      name: Concurrent Analytics
      started: 2017
      duration: 2017-Present
      title: Founder & CEO
      link: <a href="http://concurrent-analytics.com" target="_blank"> <u>www.concurrent-analytics.com</u> </a>
      description: >
        <ul><li>Created from the scratch a Kubernetes cluster for big data processing, data analytics, computing and machine learning using Apache Spark.</li>
        <li>Developed an entire infrastructure as Infrastructure-as-Code using Ansible, later rewritten using Terraform.</li>
        <li>Cluster logging&#58 Elasticserach, Kibana, Fluent Bit, Metricbeat.</li>
        <li>Cluster monitoring&#58 Prometheus and Grafana.</li>
        <li>Spark ecosystem&#58 Standalone Spark cluster with worker nodes, Spark history server, HDFS storage.</li>
        <li>Spring Boot Service as Backend with MySQL and MongoDB and Web Frontend with Angular.</li>
        <li>Autonomous TeamCity CI/CD server that reacts to webhooks and takes an automatic deploy/redeploy.</li>
        <li>All TeamCity Pipelines developed as a code with Kotlin.</li>
        <li>Nexus as a repository for artefacts and docker images.</li>
        <li>Apache Zeppelin for fast access to Spark cluster.</li>
        <li>Helm as package manager for Kubernetes.</li></ul>
      technologies: Kubernetes, Docker, Terraform, Apache Spark. HDFS, Helm. Elasticsearch, Kibana, Fluent Bit, Ansible, Prometheus, Grafana, MySQL, MongoDB, Angular, TeamCity, Kotlin, Nexus, Shell
    - project3:
      name: Words Tutor
      started: 2016
      duration: 2016-2017
      title: Founder
      link: <a href="https://play.google.com/store/apps/details?id=com.jdev.tutor" target="_blank"> <u>Words Tutor on PlayMarket</u> </a>
      description: >
        Built the "Words Tutor” Android application that helps users to learn new words in any language in a game mode. Initially developed as a client-server app and later re-developed in one
        autonomous mode.
        The "Words Tutor” app has a lot of features&#58
        <ul><li>Creating a new dictionary from MS Word/Excel and text documents;</li>
        <li>Importing dictionaries from Lingvo Tutor;</li>
        <li>Grouping renaming, deleting, sorting, moving dictionaries between groups;</li>
        <li>10 different types of trainings;</li>
        <li>Ability to monitor the learning progress words and the progress statistics after each training session and possibility to reset the study results and dictionary review;</li>
        <li>Different public dictionaries are available for each user;</li>
        <li>Instant word adding service with one click after copying;</li>
        <li>Automatic translation of the word into more than 100 languages;</li>
        <li>Add / edit / delete a word to/in an existing dictionary;</li>
        <li>Search in the dictionary by learned word or its translation;</li>
        <li>A lot of flexible settings, level of complexity for individual trainings, different themes;</li>
        <li>Flexible configurable voice synthesizer;</li></ul>
      technologies:  Java, Android
    - project4:
      name: Other
      started: 2012
      duration: 2012-2014
      description: >
        <ul><li>A chess game developed using Java Sockets and Java Swing with following features&#58 local and network game,
        2D chess board, 2-player mode, clock, chat, save/continue network game, animation during figure selection.</li>
        <li>A “Sudoku" game with game generation algorithm, level of complexity and a database storage for iPhone using Objective C and Cocoa.</li>
        <li>A “MapTracker” project developed using Android. The aim of the project is to save the GPS coordinates
        during the user movement using the background service and then to play the trip in Google 3D Maps.</li></ul>
      technologies:  Java, Java Swing, Objective C, Cocoa, Android
  educationHistory:
    - education1:
      organization: Hochschule für Technik und Wirtschaft Berlin (University of Applied Sciences)
      location: Berlin, Germany
      degree: Bachelor of Science
      major: Applied computer science (Angewandte Informatik)
      started: 2011
      duration: (2011 - 2014)
      description:
    - education2:
      organization: Hochschule Osnabrück (University of Applied Sciences)
      location: Osnabrück, Germany
      degree: Bachelor of Science
      major: Media informatics (Medieninformatik)
      started: 2008
      duration: (2008 - 2011)
      description:
    - education3:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Master of Science
      major: Computer sciences
      started: 2007
      duration: (2007 - 2008)
      description:
    - education4:
      organization: Ternopil Ivan Puluj National Technical University
      location: Ternopil, Ukraine
      degree: Bachelor of Science
      major: Computer sciences
      started: 2005
      duration: (2005 - 2007)
      description:
    - education5:
      organization: Vyacheslav Chornovil Galician College
      location: Ternopil, Ukraine
      degree: Diploma of qualified specialist degree
      major: Computer science, operation of data processing and decision systems
      started: 2001
      duration: (2001 - 2005)
      description:
  languages:
    - language1:
      name: English
      proficiency: Proficient
    - language2:
      name: German
      proficiency: Proficient
    - language3:
      name: Ukrainian
      proficiency: Native
    - language4:
      name: Russian
      proficiency: Native
  skills:
    - skill1:
      name: Kubernetes
      percentage: 70%
    - skill2:
      name: Prometheus/Grafana
      percentage: 70%
    - skill3:
      name: OpenSearch
      percentage: 50%
    - skill4:
      name: Traefik
      percentage: 70%
    - skill5:
      name: Helm
      percentage: 70%
    - skill6:
      name: Docker
      percentage: 90%
    - skill7:
      name: Java
      percentage: 100%
    - skill8:
      name: Spring / Spring Boot
      percentage: 90%
    - skill9:
      name: Jenkins
      percentage: 80%
    - skill10:
      name: Terraform
      percentage: 60%
    - skill11:
      name: Groovy
      percentage: 80%
    - skill12:
      name: Databases
      percentage: 75%
    - skill13:
      name: Python
      percentage: 65%
    - skill14:
      name: Go
      percentage: 60%
  experiences:
    - skill1:
      name: Java
      label: 12 years
      percentage: 100%
    - skill2:
      name: Spring / Spring Boot
      label: 10 years
      percentage: 80%
    - skill3:
      name: Linux
      label: 10 years
      percentage: 80%
    - skill4:
      name: Databases
      label: 10 years
      percentage: 80%
    - skill5:
      name: Jenkins
      label: 8 years
      percentage: 60%
    - skill6:
      name: Docker
      label: 7 years
      percentage: 50%
    - skill7:
      name: CI/CD
      label: 7 years
      percentage: 50%
    - skill8:
      name: Kubernetes
      label: 6 years
      percentage: 50%
    - skill9:
      name: DevOps
      label: 6 years
      percentage: 40%
    - skill10:
      name: Terraform
      label: 3 year
      percentage: 30%
  interestedon:
    - skill1:
      name: Data Engineering
      percentage: 100%
    - skill2:
      name: DevOps
      percentage: 100%
    - skill3:
      name: Clouds
      percentage: 100%
    - skill4:
      name: BigData
      percentage: 100%
    - skill5:
      name: Kubernetes
      percentage: 100%
    #    - skill6:
    #      name: Terraform
    #      percentage: 80%
    #    - skill7:
    #      name: Java
    #      percentage: 70%
    #    - skill8:
    #      name: Databases
    #      percentage: 75%
    #    - skill9:
    #      name: Python
    #      percentage: 80%
    #    - skill10:
    #      name: Go
    #      percentage: 80%
  environment_skills: [Linux/MacOS/Windows, IntelliJ IDEA, Docker, Shell, Git]
  languages_skills: [Java, Python, Go, Bash, SQL, JavaScript, Groovy]
  frameworks_skills: [Spring, Spring Boot, Apache Spark, Angular, Android SDK]
  paradigms_skills: [DevOps, Object-oriented Programming (OOP), CQRS, Agile Software Development(Scrum/Kanban), Dependency Injection, Microservices, Microservices Architecture, Continuous Integration (CI), Continuous Development (CD), Continuous Delivery (CD), REST, Unit/Integrations Testing, UML]
  storage_skills: [MySQL, Elasticsearch, Oracle, MongoDB, Couchbase, SQLite]
  tools_skills: [IntellJ IDEA, Gradle, Maven, sbt, Git, Jenkins, TeamCity, Nexus, SonarQube, Portainer, Visual Studio Code, Android Studio, Terraform, Kibana, Grafana]
  platforms_skills: [Kubernetes, Docker, Android, AWS, Vagrant, Linux, MacOS, Windows]
  libraries_skills: [Apache Lucene, Apache CXF, Jersey, RESTEasy, Flyway, Liquibase, Guava, JUnit, TestNG, Mockito, OpenAPI(Swagger), JAX-RS, Bean Validation, JPA]